apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
   replicas: 1
   template:
     metadata:
	   labels:
	   name:springboot
	spec:
	  containers:
	  - image: dockerhanson/spring-boot-mongo
		 name: springboot
		 ports:
		 - name: springboot
		   containerport: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
   name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
	  targetport: 8080
  selector:
      name: springboot
---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
   name: mongo-controller
 spec:
   replicas: 1
    template
      metadata:
        labels:
          name: mongo
spec:
   containers:
   - image: mongo
     name: mongo
     ports:
    - name: mongo
      containerport: 27017
      hostport: 27017
    volumemount:
    - name: mongo-persistent-storage
      mountpath: /data/db
   volumes:
   - name: mongo-persistent-storage
     hostpath:
      path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
   name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
	  targetport:
	selector:
	   name: mongo